### ISSUE TITLE
Uncaught ReferenceError: positionOption is not defined  at HTMLInputElement.<anonymous>

### ISSUE THREAD

**Issue by I-CRE8** [MLaritz/Vanilla-Notify#7]
using the following code inside an event listener:
` 
      vNotify.warning({
        text: 'Action cancelled, you must have at least one filter selected to use this option',
        position: positionOption.topRight,
        sticky: true
      });`
I get the following error message: Uncaught ReferenceError: positionOption is not defined at HTMLInputElement.<anonymous>

What am I doing wrong ?

**Comment by MLaritz** [comment]
positionOption is not global.  It is scoped to the vNotify object, so try:  `vNotify.positionOption.topRight`

**Comment by I-CRE8** [comment]
Thanks, that has stopped the error but the notification still appears in the default position.
Code now looks like this:
`      vNotify.positionOption.topLeft; 
      vNotify.warning({
        text: 'Action cancelled, you must have at least one filter selected to use this option',
        sticky: true
      });`

**Comment by MLaritz** [comment]
Try this:
`vNotify.warning({ text: 'Action cancelled, you must have at least one filter selected to use this option', position: vNotify.positionOption.topLeft, sticky: true });`

**Comment by I-CRE8** [comment]
Perfect, thank you.
